// packages/components/components/ui/body/body.vue
<template>
  <div
    :id="id"
    :class="`body ${format ? 'typo-format' : ''} ${
      rhythm ? 'typo-rhythm' : ''
    } ${props.class ?? ''}`"
  >
    <div
      v-if="finalSuptitle"
      :class="`body_suptitle ${typoClasses ? 'typo-suptitle' : ''}`"
      v-html="finalSuptitle"
    ></div>
    <component
      :is="`h${headingLevel.tag}`"
      :class="`body_title ${
        typoClasses ? `typo-h${headingLevel.display}` : ''
      }`"
      v-html="finalTitle"
    />
    <div
      v-if="finalSubtitle"
      :class="`body_subtitle ${typoClasses ? 'typo-subtitle' : ''}`"
      v-html="finalSubtitle"
    ></div>

    <div
      :class="`body_lead ${typoClasses ? 'typo-lead' : ''}`"
      v-html="finalLead"
    ></div>
    <div
      :class="`body_text ${typoClasses ? 'typo-p' : ''}`"
      v-html="finalText"
    ></div>

    <nav class="body_buttons" v-if="buttons?.length">
      <Button v-for="(button, i) in buttons" v-bind="button" :key="i" />
    </nav>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Button from '../button/button.vue';
import './body.css';
import type { TBody } from './body.type.js';

const props = withDefaults(defineProps<TBody>(), {
  headingLevel: () => {
    return {
      tag: 3,
      display: 3,
    };
  },
});

const finalSuptitle = computed(() => props.suptitle ?? ''),
  finalSubtitle = computed(() => props.subtitle ?? ''),
  finalTitle = computed(() => props.title ?? ''),
  finalLead = computed(() => props.lead ?? ''),
  finalText = computed(() => props.text ?? '');
</script>

// packages/components/components/ui/body/body.tsx
// import { TBody } from '@lotsof/types';
// import React from 'react';
// import './body.css';

// export default function Body(props: TBody) {
//   const Subtitle = `h${props.suptitleLevel}`,
//     Title = `h${props.titleLevel}`,
//     Suptitle = `h${props.suptitleLevel}`;

//   return (
//     <div className="body typo-rhythm typo-format">
//       <span>React</span>

//       {props.suptitle && (
//         <Suptitle className={`_suptitle typo-h${props.suptitleLevel}`}>
//           {props.suptitle}
//         </Suptitle>
//       )}

//       {props.title && (
//         <Title className={`_title typo-h${props.suptitleLevel}`}>
//           {props.suptitle}
//         </Title>
//       )}

//       {props.subtitle && (
//         <Subtitle className={`_suptitle typo-h${props.suptitleLevel}`}>
//           {props.subtitle}
//         </Subtitle>
//       )}

//       {props.lead && <p className="_lead typo-lead">{props.lead}</p>}

//       {props.text && <p className="_text typo-p">{props.text}</p>}

//       {props.buttons && (
//         <div className="_buttons">
//           {/* {props.buttons.map((button) => (
//             // <Button {...button} />
//           ))} */}
//         </div>
//       )}

//       {/* @if (is_array($buttons) && count($buttons) > 0)
//         <div className="_buttons">
//             @foreach ($buttons as $button)
//                 @include ('button.button', (array) $button)
//             @endforeach
//         </div>
//     @endif */}
//     </div>
//   );
// }
